### ISSUE TITLE
Now modules added but have not tested with the latest Slicer after removing the diffusion part

### ISSUE THREAD

**Issue by zhangfanmark** [SlicerDMRI/new-modules#1]
Two new modules of FiberTractClean and FiberEndPointFromLabelMap were added, with the following tests: 
1. With Slicer before removing DMRI with/without ctest cases (passed).
2. With Slicer after removing DMRI without ctest cases (passed).  
3. Have not tested with Slicer after removing DMRI with ctest cases, since the latest Slicer cannot be compiled with BULD_TESTING on.

**Comment by zhangfanmark** [comment]
Hi @ihnorton @ljod 

I have put the modules in this repo and will close the branch in my SlicerDMRI. Let's work in this repo on the two modules. 

Regarding the above issue, I'll test the modules after the mentioned bug is fixed. Please let me know if you get any information about the bug fix. I'll keep eyes on this as well. Thanks! 

Regards,
Fan

**Comment by ihnorton** [comment]
> Have not tested with Slicer after removing DMRI with ctest cases, since the latest Slicer cannot be compiled with BULD_TESTING on.

ref:
http://slicer-users.65878.n3.nabble.com/Slicer-download-URLs-marked-as-malware-by-corporate-IT-rules-tp4029813.html
http://slicer-devel.65872.n3.nabble.com/MIDAS-over-SSL-td4035873.html

**Comment by ihnorton** [comment]
[edit: wrong issue, links corrected above]

**Comment by ihnorton** [comment]
Fixed.
